name: Daily Key Generator

on:
  schedule:
    - cron: '0 0 * * *'   # tiap hari jam 00:00 UTC
  workflow_dispatch:     # bisa run manual

jobs:
  generate-key:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate random key
        run: |
          KEY="MUNCAK-$(openssl rand -hex 4 | tr 'a-f' 'A-F')"
          echo "$KEY" > key

      - name: Commit & push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add key
          git commit -m "ðŸ”‘ Daily key update"
          git push
